[project]
name = "biwa-dataplotter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "pandas>=2.3.3",
    "paramiko>=4.0.0",
    "pyqt6>=6.10.2",
    "pyqtgraph>=0.14.0",
]
